<?php
/**
 * Created by PhpStorm.
 * User: 81908
 * Date: 2017/4/25
 * Time: 16:20
 */
namespace app\user\controller;
use app\common\controller\Base;

class Common extends Base{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}