<?php
/**
 * Created by PhpStorm.
 * User: 81908
 * Date: 2017/4/25
 * Time: 16:18
 */
namespace app\user\controller;
use app\user\controller\Common;
use think\Db;

/**
 * 博客首页
 * Class Customer
 * @package app\user\controller
 */
class Customer extends Common{

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index(){
//        halt($this->request()->session());
        $where['article.status'] = 1;
        $sql = Db::name('article')
                        ->alias('article')
                        ->join('bn_article_classifty class', 'article.ac_id = class.id')
                        ->join('bn_user user', 'article.u_id = user.id')
                        ->where($where)
                        ->field('article.*, class.cname, user.name')
                        ->order('article.top DESC, article.create_time DESC');
        $article_list = $sql->paginate(10);
        $new_article_list = $sql->select();
        foreach ($article_list as $k => $v){
            $article_list[$k]['content'] = htmlspecialchars_decode($v['content']);
        }
        $this->assign(['article_list'=>$article_list, 'new_article_list'=>$new_article_list]);
        return $this->fetch();
    }
}